

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: peacerotimi6
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    secrets:
      - db_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    depends_on:
      - database
    secrets:
      - db_pass
    environment:
      DB_HOST: database
      DB_NAME: mydatabase
      DB_USER: peacerotimi6
    ports:
      - "5050:5050"

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://peacerotimi6@database:5432/mydatabase?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - database

secrets:
  db_pass:
    file: ./db_pass.txt

volumes:
  pgdata:
